import { formatProjectEntryLinkExpression } from "../../../src/templates/defaultBasesFiles";
import { extractBasesFilterDefaults } from "../../../src/bases/basesFilterDefaults";
import type { TaskCreationFieldMapper } from "../../../src/bases/basesTaskCreation";
import type { FieldMapping } from "../../../src/types";

const fieldMapping: FieldMapping = {
	title: "title",
	status: "status",
	priority: "priority",
	due: "due",
	scheduled: "scheduled",
	contexts: "contexts",
	projects: "projects",
	timeEstimate: "timeEstimate",
	completedDate: "completedDate",
	dateCreated: "dateCreated",
	dateModified: "dateModified",
	recurrence: "recurrence",
	recurrenceAnchor: "recurrence_anchor",
	archiveTag: "archived",
	timeEntries: "timeEntries",
	completeInstances: "complete_instances",
	skippedInstances: "skipped_instances",
	blockedBy: "blockedBy",
	pomodoros: "pomodoros",
	icsEventId: "icsEventId",
	icsEventTag: "icsEventTag",
	googleCalendarEventId: "googleCalendarEventId",
	reminders: "reminders",
	sortOrder: "sort_order",
};

function createFieldMapper(overrides: Partial<FieldMapping> = {}): TaskCreationFieldMapper {
	const mapping = { ...fieldMapping, ...overrides };
	return {
		toUserField: (field) => mapping[field],
	};
}

describe("Bases filter defaults", () => {
	it.each([
		'list(note.projects).map("constant").contains(this.file.asLink())',
		'list(note.projects).map(value).filter(false).contains(this.file.asLink())',
		'!file.hasLink(this.file) && note.status == "done"',
		'this.note.status == "done"',
		`file.hasLink(this.file) || list(note.projects).map(${formatProjectEntryLinkExpression("value")}).contains(this.file.asLink())`,
	])("does not infer defaults from transformed or source-note expressions: %s", (text) => {
		expect(extractBasesFilterDefaults({
			config: { filters: { rule: { text } } },
			fieldMapper: createFieldMapper(), taskTag: "task", currentFileLink: "[[Current]]",
		})).toEqual({});
	});

	it("recognizes the generated normalization with a mapped project field", () => {
		const text = `file.hasLink(this.file) && list(note.projectLinks).map(${formatProjectEntryLinkExpression("value")}).contains(this.file.asLink())`;
		expect(extractBasesFilterDefaults({
			config: { filters: { rule: { text } } },
			fieldMapper: createFieldMapper({ projects: "projectLinks" }),
			taskTag: "task", currentFileLink: "[[Current]]",
		})).toEqual({ projectLinks: ["[[Current]]"] });
	});
	it("extracts deterministic task defaults from Base filters", () => {
		const defaults = extractBasesFilterDefaults({
			config: {
				query: {
					filters: {
						conjunction: "and",
						filters: [
							{ rule: { text: 'file.hasTag("task")' } },
							{ rule: { text: 'file.hasTag("client")' } },
							{ rule: { text: 'note.state == "doing"' } },
							{ rule: { text: 'note.title == "Escaped \\"Title\\""' } },
							{ rule: { text: 'list(note.projectLinks).contains("[[Alpha]]")' } },
							{
								rule: {
									text: "list(note.projectLinks).contains(this.file.asLink())",
								},
							},
							{ rule: { text: 'task.areas.contains("work")' } },
						],
					},
				},
				filters: {
					rule: { text: 'note.effort == "8"' },
				},
			},
			fieldMapper: createFieldMapper({
				status: "state",
				projects: "projectLinks",
				contexts: "areas",
			}),
			taskTag: "task",
			userFields: [{ key: "effort" }],
			currentFileLink: "[[Current]]",
		});

		expect(defaults).toEqual({
			tags: ["client"],
			state: "doing",
			title: 'Escaped "Title"',
			projectLinks: ["[[Alpha]]", "[[Current]]"],
			areas: ["work"],
			effort: "8",
		});
	});

	it("ignores ambiguous OR filters and unknown properties", () => {
		const defaults = extractBasesFilterDefaults({
			config: {
				filters: {
					conjunction: "and",
					filters: [
						{
							conjunction: "or",
							filters: [
								{ rule: { text: 'note.status == "open"' } },
								{ rule: { text: 'note.status == "done"' } },
							],
						},
						{ rule: { text: 'note.unknown == "ignored"' } },
						{ rule: { text: 'note.due == "2026-05-20"' } },
						{ rule: { text: 'note.due == "2026-05-21"' } },
					],
				},
			},
			fieldMapper: createFieldMapper(),
			taskTag: "task",
		});

		expect(defaults).toEqual({
			due: "2026-05-20",
		});
	});

	it("skips this.file.asLink defaults when no current file link is available", () => {
		const defaults = extractBasesFilterDefaults({
			config: {
				filters: {
					rule: { text: "list(note.projects).contains(this.file.asLink())" },
				},
			},
			fieldMapper: createFieldMapper(),
			taskTag: "task",
			currentFileLink: null,
		});

		expect(defaults).toEqual({});
	});

	// Regression: issue #2043. The default relationships Subtasks filter
	// generated by `formatProjectEntryLinkExpression` in `defaultBasesFiles.ts`
	// emits `file.hasLink(this.file) && list(note.PROP).map(<link-normalizer>).asLink()).contains(this.file.asLink())`.
	// The `currentFileContainsMatch` regex captures the entire conjunction, so
	// the parser must strip the `&&` left side and the generated `.map(...).asLink()`
	// chain before extracting the property name.
	it("extracts project default from generated `file.hasLink(this.file) &&` conjunction filter (#2043)", () => {
		const generatedRule =
			'file.hasLink(this.file) && list(note.projects).map(file(value.replace(/^\\[[^\\]]+\\]\\((.*)\\)$/, "$1").replace(/%20/g, " ")).asLink()).contains(this.file.asLink())';

		const defaults = extractBasesFilterDefaults({
			config: {
				filters: {
					rule: { text: generatedRule },
				},
			},
			fieldMapper: createFieldMapper(),
			taskTag: "task",
			currentFileLink: "[[Current]]",
		});

		expect(defaults).toEqual({
			projects: ["[[Current]]"],
		});
	});

	it("extracts user-defined field from generated conjunction + map filter (#2043)", () => {
		const generatedRule =
			'file.hasLink(this.file) && list(note.customField).map(file(value.replace(/^\\[[^\\]]+\\]\\((.*)\\)$/, "$1").replace(/%20/g, " ")).asLink()).contains(this.file.asLink())';

		const defaults = extractBasesFilterDefaults({
			config: {
				filters: {
					rule: { text: generatedRule },
				},
			},
			fieldMapper: createFieldMapper(),
			taskTag: "task",
			userFields: [{ key: "customField" }],
			currentFileLink: "[[Current]]",
		});

		// Unknown user-defined fields fall through to scalar storage in
		// `addFrontmatterDefault` (the list-merge path is reserved for the
		// core list fields: tags, contexts, projects, blockedBy).
		expect(defaults).toEqual({
			customField: "[[Current]]",
		});
	});

	it("falls back gracefully when current file link is missing for the generated filter (#2043)", () => {
		const generatedRule =
			'file.hasLink(this.file) && list(note.projects).map(file(value.replace(/^\\[[^\\]]+\\]\\((.*)\\)$/, "$1").replace(/%20/g, " ")).asLink()).contains(this.file.asLink())';

		const defaults = extractBasesFilterDefaults({
			config: {
				filters: {
					rule: { text: generatedRule },
				},
			},
			fieldMapper: createFieldMapper(),
			taskTag: "task",
			currentFileLink: null,
		});

		expect(defaults).toEqual({});
	});
});
